### ISSUE TITLE
add line to install.inf

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_codeium#1]
to [info]:
`os=win,linux,macos`

**Comment by Alexey-T** [comment]
https://wiki.freepascal.org/CudaText_files_formats#Install.inf_supported_.22os.22_values

**Comment by veksha** [comment]
is this ok? `win-x86_64,linux-arm,linux-x86_64,macos-arm,macos-x86_64`

**Comment by Alexey-T** [comment]
64-bit ARM is 'aarch64', not 'arm'.

**Comment by veksha** [comment]
changed.
