### ISSUE TITLE
on answering of 2nd question, I got old ui-tab title

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_codeium#10]
![Screenshot from 2023-05-15 23-48-41](https://github.com/veksha/cuda_codeium/assets/4154978/8a55b2dc-9c75-4400-a23d-da5baf02fadd)

**Comment by veksha** [comment]
and if you ask him "more". should tab title be renamed to "Bot | more"?

**Comment by Alexey-T** [comment]
Better to always rename (special word list is bad )

**Comment by veksha** [comment]
added bc9c19d
