### ISSUE TITLE
stop bot by pressing ESC/Space/Enter

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_codeium#12]
@Alexey-T, added subj. you can publish new version.

**Comment by Alexey-T** [comment]
Done

**Comment by Alexey-T** [comment]
you can speedup it.

move `on_key` to separate section in .inf.
add for this new section "keys" filter.

https://wiki.freepascal.org/CudaText_files_formats

Only for "section=events":

    "events": comma-separated list of events to handle in plugin, e.g. "events=on_change,on_caret".
    "keys": supported only for several events:
        for "on_key": comma-separated list of int key codes to handle in event, e.g. "keys=9" means that event is only called for key code 9 (Tab char).
        for "on_open" / "on_open_pre": comma-separated list of lower-case file extensions, without leading dot, to handle in event.

**Comment by veksha** [comment]
done: 04f527b

**Comment by veksha** [comment]
Is it ok?

**Comment by Alexey-T** [comment]
Yes, thanks.
