### ISSUE TITLE
I only "Got 0 items"

### ISSUE THREAD

**Issue by TomBraider42** [veksha/cuda_codeium#14]
The Chat works, but "Get completions" doesn't get any item.
"Fibonacci" gets in PHP a list of numbers, works.
"create array with 5 strings" gets 0 items.
Tested on Windows 11 x64. Any Tip?

**Comment by Alexey-T** [comment]
'create array' must be written in comment, no?
I got this

![php](https://github.com/veksha/cuda_codeium/assets/4154978/23fed123-dff7-4860-9c6d-56af3491a3e1)

**Comment by Alexey-T** [comment]
and this, note that I wrote `array1 =`.
![php2](https://github.com/veksha/cuda_codeium/assets/4154978/c1b1c303-b0cf-4bf7-a0db-97780b4a88ad)

**Comment by TomBraider42** [comment]
OK, i have to type the comment AND Enter and in the new line to press the hotkey.
I pressed the hotkey at the end of the comment/text line.
