### ISSUE TITLE
on macos sometimes current tab is used for chat

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_codeium#15]
this bug is similar to bug in cuda_hotspots: https://github.com/veksha/cuda_hotspots/issues/22
because we use `ed.cmd(cmds.cmd_FileNew)` and we assume that we now can use `ed` var that will point to new tab editor, but this is not always the case on macOS.

fixed.
@Alexey-T, can you update `cuda_codeium` it in addon manager, please?

**Comment by Alexey-T** [comment]
updated: Codeium, Hotspots.
