### ISSUE TITLE
use lexer Markdown for chat-reply?

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_codeium#9]
lexer fits:

![Screenshot from 2023-05-15 23-40-16](https://github.com/veksha/cuda_codeium/assets/4154978/08764fbd-7f58-43a5-869a-dd2dce3d53fa)

**Comment by veksha** [comment]
i see that for me it very rarely annotates a block of code with the name of a language.

<pre>
``` NO TEXT HERE
code with no colors
```
</pre>

with Log lexer it has at least some colors.

![image](https://github.com/veksha/cuda_codeium/assets/275333/af61356e-f886-43c6-95c0-0e5c089f2cff)

![image](https://github.com/veksha/cuda_codeium/assets/275333/5a09fa8e-72ac-4037-bf7a-b0173fbb2e41)

**Comment by veksha** [comment]
can we somehow make new lexer for this? and use in this plugin only.

**Comment by veksha** [comment]
ok. changed to Markdown.

maybe i should try to autodetect and insert lexer name to code blocks with empty language identifier
